apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-server
  labels:
    app: user-server
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: user-server
  template:
    metadata:
      labels:
        app: user-server
    spec:
      containers:
        - name: user-server
          image: registry.cn-hangzhou.aliyuncs.com/qvbilam/user-server:1.0.0
          imagePullPolicy: IfNotPresent
          ports: # 容器内部使用端口
            - containerPort: 9501
          env:
            - name: SERVER_NAME
              valueFrom:
                configMapKeyRef:
                  key: server_name
                  name: user
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  key: mysql_host
                  name: user
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  key: mysql_port
                  name: user
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: mysql_user
                  name: user
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: mysql_password
                  name: user
            - name: MYSQL_DATABSE
              valueFrom:
                configMapKeyRef:
                  key: mysql_database
                  name: user
            - name: USER-SERVER_NAME
              valueFrom:
                configMapKeyRef:
                  key: user-server_name
                  name: user
            - name: USER-SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  key: user-server_host
                  name: user
            - name: USER-SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  key: user-server_port
                  name: user
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
      imagePullSecrets:
        - name: ali-image-key