apiVersion: "v1"
kind: ConfigMap
metadata:
  name: user
  labels:
    app: user
data:
  # 服务配置
  server_name: user-server

  # jwt 配置
  jwt_key: Ep<4Iy#2Im~4Ab^8Px;6Oj.5Hi^8Yh)6
  jwt_expire: "86400"
  jwt_issuer: qvbilam-user

  # mysql 配置
  db_host: docker.for.mac.host.internal
  db_port: "3306"
  db_user: root
  db_password: root
  db_database: qvbilam_user

  # redis 配置
  redis_host: docker.for.mac.host.internal
  redis_port: "6379"
  redis_password: ""
  redis_database: "0"

  # es 配置
  es_host: docker.for.mac.host.internal
  es_port: "9200"
