# user.deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-server
  labels:
    app: user-server
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: user-server
  template:
    metadata:
      labels:
        app: user-server
        version: v1.0
    spec:
      containers:
        - name: user-server
          image: registry.cn-hangzhou.aliyuncs.com/qvbilam/api-server-user:1.0.0
          # 不存在拉取
          # imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          ports: # 容器内部使用端口
            - containerPort: 9501
          env:
            # 服务配置
            - name: SERVER_NAME
              valueFrom:
                configMapKeyRef:
                  key: server_name
                  name: user

            # jwt 配置
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  key: jwt_key
                  name: user
            - name: JWT_EXPIRE
              valueFrom:
                secretKeyRef:
                  key: jwt_expire
                  name: user
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  key: jwt_issuer
                  name: user

            # 数据库配置
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: db_host
                  name: user
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  key: db_port
                  name: user
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: db_user
                  name: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db_password
                  name: user
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: db_database
                  name: user

            # es 配置
            - name: ES_HOST
              valueFrom:
                secretKeyRef:
                  key: es_host
                  name: user
            - name: ES_PORT
              valueFrom:
                secretKeyRef:
                  key: es_port
                  name: user

            # 缓存配置
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  key: redis_host
                  name: user
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  key: redis_port
                  name: user
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis_password
                  name: user
            - name: REDIS_DATABASE
              valueFrom:
                secretKeyRef:
                  key: redis_database
                  name: user

            # user-server
            - name: USER_SERVER_NAME
              valueFrom:
                configMapKeyRef:
                  key: user_server_name
                  name: public
            - name: USER_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  key: user_server_host
                  name: public
            - name: USER_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  key: user_server_port
                  name: public
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
      imagePullSecrets:
        - name: ali-image-key