apiVersion: v1
kind: Service
metadata:
  name: user-server
spec:
  selector:
    app: user-server
  ports:
    - name: grpc-user-server
      protocol: TCP
      port: 9801
      targetPort: 9501
  type: LoadBalancer